model_inputs:
  lstm:
  - text_raw_indices
  td_lstm: 
  - text_left_with_aspect_indices
  - text_right_with_aspect_indices
  ian: 
  - text_raw_indices
  - aspect_indices
  ram: 
  - text_raw_indices
  - aspect_indices
  - text_left_indices
  tnet_lf: 
  - text_raw_indices
  - aspect_indices
  - aspect_in_text
  aen_bert: 
  - text_raw_bert_indices
  - aspect_bert_indices
  lcf_bert: 
  - text_bert_indices
  - bert_segments_ids
  - text_raw_bert_indices
  - aspect_bert_indices
  lcf_albert: 
  - text_bert_indices
  - bert_segments_ids
  - text_raw_bert_indices
  - aspect_bert_indices

datasets:
  twitter:
    train: ./datasets/acl-14-short-data/train.raw
    test: ./datasets/acl-14-short-data/test.raw
  restaurant:
    train: ./datasets/semeval14/Restaurants_Train.xml.seg
    test: ./datasets/semeval14/Restaurants_Test_Gold.xml.seg
  laptop:
    train: ./datasets/semeval14/Laptops_Train.xml.seg
    test: ./datasets/semeval14/Laptops_Test_Gold.xml.seg
