model_inputs:
  lstm:
  - text_raw_indices
  td_lstm: 
  - text_left_with_aspect_indices
  - text_right_with_aspect_indices
  ian: 
  - text_raw_indices
  - aspect_indices
  ram: 
  - text_raw_indices
  - aspect_indices
  - text_left_indices
  tnet_lf: 
  - text_raw_indices
  - aspect_indices
  - aspect_in_text
  aen_bert: 
  - text_raw_bert_indices
  - aspect_bert_indices
  lcf_bert: 
  - text_bert_indices
  - bert_segments_ids
  - text_raw_bert_indices
  - aspect_bert_indices

datasets:
  strise_neu_twitter:
    train: ../REPO/dataset/graphql-topic-downloads/filtered/combined_neu.xml.seg
    test: ./datasets/acl-14-short-data/test.raw
  strise_neu_rest:
    train: ../REPO/dataset/graphql-topic-downloads/filtered/combined_neu.xml.seg
    test: ./datasets/semeval14/Restaurants_Test_Gold.xml.seg
  strise_neu_laptop:
    train: ../REPO/dataset/graphql-topic-downloads/filtered/combined_neu.xml.seg
    test: ./datasets/semeval14/Laptops_Test_Gold.xml.seg
  strise_neutral:
    train: ../REPO/dataset/graphql-topic-downloads/filtered/train_neu.xml.seg
    test: ../REPO/dataset/graphql-topic-downloads/filtered/test_neu.xml.seg
  strise:
    train: ../REPO/dataset/graphql-topic-downloads/filtered/train.xml.seg
    test: ../REPO/dataset/graphql-topic-downloads/filtered/test.xml.seg
  twitter:
    train: ./datasets/acl-14-short-data/train.raw
    test: ./datasets/acl-14-short-data/test.raw
  restaurant:
    train: ./datasets/semeval14/Restaurants_Train.xml.seg
    test: ./datasets/semeval14/Restaurants_Test_Gold.xml.seg
  restaurant_coref_maintarget:
    train: ./datasets/semeval14/Restaurants_coref_train_main_target.seg
    test: ./datasets/semeval14/Restaurants_Test_Gold.xml.seg
  restaurant_coref_gold_eval:
    train: ./datasets/semeval14/Restaurants_coref_train.seg
    test: ./datasets/semeval14/Restaurants_Test_Gold.xml.seg
  laptop:
    train: ./datasets/semeval14/Laptops_Train.xml.seg
    test: ./datasets/semeval14/Laptops_Test_Gold.xml.seg
  all_combined:
    train: ./datasets/MASS.raw
    test: ./datasets/semeval14/Restaurants_Test_Gold.xml.seg
